use-sort:
    group:
        - _main
    group-type: each
    sort-type: alph
    sort-direction: asc
strict: true
header: |
    /*
     * This file is part of the {{ project_name }}
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     *
     * Feel free to edit as you please, and have fun.
     *
     * @author {{ author_name }}
     */