bundles: Service\ServiceBundle
routes:
    - "@ServiceBundle/Resources/config/routing.yml"
config:

    parameters:
        locale: en
        kernel.secret: d7f9d7f87d98fd

    framework:
        form: false
        assets: false
        session:
            handler_id: null
        php_errors:
            log: true